### PR TITLE
Implement load context and build quoting emitter

### LINKED ISSUE #121: mscorlib is not referenced
Hello,

First of all: Thank you for this module.

When I import platyPS, before I load powershell-yaml, I get the following issue:

> (7,36): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. public class StringQuotingEmitter: ChainedEventEmitter { 

If I load powershell-yaml before platyPS, the import of platyPS I get:

> Assembly with same name is already loaded

I found out, that both modules use YamlDotNet.dll but in different versions. Both outdated, but this is not the issue.
I think, there are patterns to solve this: https://github.com/jborean93/PowerShell-ALC contains an example.

### LINKED ISSUE #126: Move add-type to compilation
Using [profiler](https://github.com/nohwnd/profiler) I found out that your module spends 77% of the time it takes to import compiling type that you can most likely ship in one of your assemblies. Please consider moving it there.

You spend 77% of time in Add-Type.

```powershell
Install-Module Profiler

Get-Module powershell-yaml | Remove-Module
$trace = Trace-Script {
	Import-Module powershell-yaml
}

$trace.Top50SelfDuration | Select -First 10
```

```
SelfPercent SelfDuration     Percent Duration         HitCount File                                Line Module          Function              Text
----------- ------------     ------- --------         -------- ----                                ---- ------          --------              ----
     77,219 00:00:00.1675183  77,219 00:00:00.1675183        1 powershell-yaml.psm1                 376 powershell-yaml                       Add-Type -TypeDefinition $stringQuotingEmitterSource -ReferencedAssemblies $referenceList -Language CSharp -CompilerOptions "-nowarn:1701"
      5,425 00:00:00.0117691   5,425 00:00:00.0117691        2 Load-Assemblies.ps1                   60                 Initialize-Assemblies }
       3,08 00:00:00.0066826    3,08 00:00:00.0066826       11 Load-Assemblies.ps1                   56 powershell-yaml Initialize-Assemblies $i -notin $yaml.DefinedTypes.Name
      2,937 00:00:00.0063710   2,937 00:00:00.0063710        1 powershell-yaml.psd1                  22                                       @{…
      2,139 00:00:00.0046412  87,089 00:00:00.1889306        1 powershell-yaml.psm1                  30 powershell-yaml                       . $here\Load-Assemblies.ps1
      1,608 00:00:00.0034887   1,608 00:00:00.0034887        1 powershell-yaml.psm1                 375 powershell-yaml                       $referenceList += [IO.Directory]::GetFiles([IO.Path]::Combine($PSHOME, 'ref'), 'netstandard.dll', [IO.SearchOption]::TopDirectoryOnly)
      1,316 00:00:00.0028541  99,979 00:00:00.2168960        1 05_module-import-powershellyaml.ps1    5                                       Import-Module powershell-yaml
      1,058 00:00:00.0022951   1,058 00:00:00.0022951        1 powershell-yaml.psm1                 372 powershell-yaml                       !([System.Management.Automation.PSTypeName]'StringQuotingEmitter').Type
      0,753 00:00:00.0016334   0,753 00:00:00.0016334        1 Load-Assemblies.ps1                   28                 Load-Assembly         [Reflection.Assembly]::LoadFrom($assemblies["core"])
      0,705 00:00:00.0015302   0,705 00:00:00.0015302        1 powershell-yaml.psm1                  27 powershell-yaml                       $infinityRegex = [regex]::new('^[-+]?(\.inf|\.Inf|\.INF)$', "Compiled, CultureInvariant")
```

### PR DESCRIPTION
**Pull request by gabriel-samfira**
This change implements Assembly Load Contexts and builds the string quoting emitter into a dll so it doesn't have to be built every time this gets imported.

This also bumps the minimum powershell version to `6.0` due to the use of `System.Runtime.Loader.AssemblyLoadContext`.

Using this module should no longer rely on the Global Assembly Context, and should make this usable along side any other module that tries to load `YamlDotNet`:

```powershell
# Get the Global Assembly Context
PS /home/gabriel/powershell-yaml> $gac = ([System.Runtime.Loader.AssemblyLoadContext]::All | ? {$_.Name -eq 'Default'})
# Check if there are any YamlDotNet assemblies loaded.                      
PS /home/gabriel/powershell-yaml> $gac.Assemblies | ? {$_.Location -like "*powershell-yaml*" }                         
PS /home/gabriel/powershell-yaml> 
# The powershell-yaml module creates a new ALC called "powershellyaml". Check if it's there. It shouldn't be, we have not yet loaded the module.
PS /home/gabriel/powershell-yaml> [System.Runtime.Loader.AssemblyLoadContext]::All | ? {$_.Name -eq 'powershellyaml'}
PS /home/gabriel/powershell-yaml>
# import the module 
PS /home/gabriel/powershell-yaml> Import-Module ./powershell-yaml.psd1
# Check again
PS /home/gabriel/powershell-yaml> [System.Runtime.Loader.AssemblyLoadContext]::All | ? {$_.Name -eq 'powershellyaml'}

Assemblies                                                                                                                                            IsCollectible Name
----------                                                                                                                                            ------------- ----
{YamlDotNet, Version=13.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e, jbtx4qo5.tda, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null}          True powershellyaml

PS /home/gabriel/powershell-yaml> $pwshALC = ([System.Runtime.Loader.AssemblyLoadContext]::All | ? {$_.Name -eq 'powershellyaml'})
# List loaded assemblies in this context
PS /home/gabriel/powershell-yaml> $pwshALC.Assemblies | ? {$_.Location -like "*powershell-yaml*" }                                

GAC    Version        Location
---    -------        --------
False  v4.0.30319     /home/gabriel/powershell-yaml/lib/netstandard2.1/YamlDotNet.dll
False  v4.0.30319     /home/gabriel/powershell-yaml/lib/netstandard2.1/StringQuotingEmitter.dll

PS /home/gabriel/powershell-yaml> $gac = ([System.Runtime.Loader.AssemblyLoadContext]::All | ? {$_.Name -eq 'Default'})           
PS /home/gabriel/powershell-yaml> 
# As we can see, the assemblies are not loaded in the global context.
PS /home/gabriel/powershell-yaml> $gac.Assemblies | ? {$_.Location -like "*powershell-yaml*" }                                    
PS /home/gabriel/powershell-yaml> 

# Load the same assemblies in the GAC
PS /home/gabriel/powershell-yaml> [System.Reflection.Assembly]::LoadFrom("/home/gabriel/powershell-yaml/lib/net45/YamlDotNet.dll")

GAC    Version        Location
---    -------        --------
False  v4.0.30319     /home/gabriel/powershell-yaml/lib/net45/YamlDotNet.dll

PS /home/gabriel/powershell-yaml> $gac.Assemblies | ? {$_.Location -like "*powershell-yaml*" }                                    

GAC    Version        Location
---    -------        --------
False  v4.0.30319     /home/gabriel/powershell-yaml/lib/net45/YamlDotNet.dll

# Try to load some really old version in the GAC
PS /home/gabriel/powershell-yaml> [System.Reflection.Assembly]::LoadFrom("/home/gabriel/really-old-powershell-yaml/lib/net45/YamlDotNet.dll")
MethodInvocationException: Exception calling "LoadFrom" with "1" argument(s): "Assembly with same name is already loaded"

PS /home/gabriel/powershell-yaml> remove-Module powershell-yaml
PS /home/gabriel/powershell-yaml> Import-Module ./powershell-yaml.psd1                                                                       
# Test that powershell-yaml still works
PS /home/gabriel/powershell-yaml> Invoke-Pester                                                                                             

Starting discovery in 1 files.
Discovery found 38 tests in 423ms.
Running tests.
[+] /home/gabriel/powershell-yaml/Tests/powershell-yaml.Tests.ps1 1.42s (743ms|266ms)
Tests completed in 1.43s
Tests Passed: 38, Failed: 0, Skipped: 0, Inconclusive: 0, NotRun: 0
flection.Assembly]::LoadFrom("/home/gabriel/powershell-yaml/lib/net45/YamlDotNet.dll")

GAC    Version        Location
---    -------        --------
False  v4.0.30319     /home/gabriel/powershell-yaml/lib/net45/YamlDotNet.dll

PS /home/gabriel/powershell-yaml> $gac.Assemblies | ? {$_.Location -like "*powershell-yaml*" }                                    

GAC    Version        Location
---    -------        --------
False  v4.0.30319     /home/gabriel/powershell-yaml/lib/net45/YamlDotNet.dll

PS /home/gabriel/powershell-yaml> [System.Reflection.Assembly]::LoadFrom("/home/gabriel/really-old-powershell-yaml/lib/net45/YamlDotNet.dll")
MethodInvocationException: Exception calling "LoadFrom" with "1" argument(s): "Assembly with same name is already loaded"
PS /home/gabriel/powershell-yaml> 
PS /home/gabriel/powershell-yaml> remove-Module powershell-yaml
PS /home/gabriel/powershell-yaml> Import-Module ./powershell-yaml.psd1                                                                       
PS /home/gabriel/powershell-yaml> Invoke-Pester                                                                                             

Starting discovery in 1 files.
Discovery found 38 tests in 423ms.
Running tests.
[+] /home/gabriel/powershell-yaml/Tests/powershell-yaml.Tests.ps1 1.42s (743ms|266ms)
Tests completed in 1.43s
Tests Passed: 38, Failed: 0, Skipped: 0, Inconclusive: 0, NotRun: 0
```

Fixes #126
Fixes #121

### CODE REVIEW

**Comment by splatteredbits** [comment]
Making the minimum version PowerShell 6.0 would mean we'd have to switch to another Yaml PowerShell module. We are still primarily a Windows PowerShell 5.1 organization. Please do not make this change!

**Comment by splatteredbits** [comment]
I do not think you need to use Assembly Load Contexts. .NET will happily load assemblies with the same name but different versions. I don't know what it uses to pick which assembly wins when referencing types, but you can use PowerShell magic to load types from a specific assembly. We do it in our `TlsCertificateValidation` PowerShell module. 

[Here](https://github.com/webmd-health-services/TlsCertificateValidation/blob/main/TlsCertificateValidation/TlsCertificateValidation.psm1#L23-L26) we load a type from the assembly that ships with the module:

```powershell
$assemblyPath = Join-Path -Path $script:moduleRoot -ChildPath 'bin\TlsCertificateValidation.dll' -Resolve
$assembly = [AppDomain]::CurrentDomain.GetAssemblies() | Where-Object 'Location' -EQ $assemblyPath
$assemblyTypes = $assembly.GetTypes()
$script:serverCertCallbackShim = $assemblyTypes | Where-Object 'Name' -EQ 'ServerCertificateCallbackShim'
```

Then we call a static method on it [here](https://github.com/webmd-health-services/TlsCertificateValidation/blob/c0e5d2de77b7d1a9c1864edd20995baf5a605297/TlsCertificateValidation/Functions/Set-TlsCertificateValidator.ps1#L37):

```powershell
    $script:serverCertCallbackShim::RegisterScriptBlockValidator($ScriptBlock)
```

**Comment by gabriel-samfira** [comment]
> Making the minimum version PowerShell 6.0 would mean we'd have to switch to another Yaml PowerShell module. We are still primarily a Windows PowerShell 5.1 organization. Please do not make this change!

Understood. Will look for alternate path to allow load contexts and support 5.1.

**Comment by splatteredbits** [comment]
More notes: `Add-Type` won't load an assembly with a duplicate name. But `[Reflection.Assembly]::LoadFrom` will:

image

**Comment by gabriel-samfira** [comment]
> More notes: `Add-Type` won't load an assembly with a duplicate name. But `[Reflection.Assembly]::LoadFrom` will:
> 
> image
> 
> And I believe if your module's manifest includes an assembly to load, PowerShell uses `[Reflection.Assembly]::LoadFrom` to load it. But I could be mistaken on that.

The issue was never that powershell-yaml would fail to load if YamlDotNet was already loaded. We always supported that scenario. The problem in some cases is that other modules fail to load if powershell-yaml is loaded first. See [this issue](https://github.com/PowerShell/platyPS/issues/481) as an example. That issue was fixed, but this may happen in other cases as well.

Load contexts fixes this as they give us our own context to work with. Assemblies we load won't be loaded in the GAC, so other modules are free to use it as they please, and if it fails, at least it's not our fault :smile:.

That being said, let's do the following:

* Please remove the `Fixes` line from your PR. The issue you link to is more about load contexts than the failure to load mscorelib. And I would like to review and merge your change without closing that issue.
* After we merge your change, I will incorporate the test and the change into this PR
* I will then need your help to test on powershell 5.1

Sadly, GitHub have removed Windows Server 2016 runners back in 2022, so we can't automatically test. I will look into potentially adding a self hosted runner with 2016. Good excuse to dogfood [on one of our other projects](https://github.com/cloudbase/garm).

**Comment by splatteredbits** [comment]
New versions of Windows should still have Windows PowerShell. Can you update the build scripts to run `powershell.exe` on those servers?

**Comment by gabriel-samfira** [comment]
Creating a Windows Server 2016 VM so I can tests this stuff on 5.1 as well. Until we have a proper runner, manual testing it is :sweat_smile: .

**Comment by gabriel-samfira** [comment]
I ran the tests on Windows server 2016, which runs `5.1.14393.693`. 

image

Can you also test on your side to make sure this PR works for you?

**Comment by gabriel-samfira** [comment]
I also added 2 new jobs that tests on Powershell Desktop.

**Comment by gabriel-samfira** [comment]
The new `StringQuotingEmitter.dll` is essentially the source code outputed as a `dll`. Loading it should work and should be a lot faster than compiling the source on every first time import into a powershell session.

**Comment by gabriel-samfira** [comment]
Merged your PR and rebased this one on top. If you could test this PR out in your env, that would be amazing. I tested it on a Windows Server 2016 and it worked, but another test on someone else's system would be great. I don't want to break anything.

**Comment by KhoiKy** [comment]
@gabriel-samfira When testing against this specific branch of this module, I am no longer seeing the error we were experiencing before. This looks good to me.

**Comment by gabriel-samfira** [comment]
@splatteredbits could you PTAL at this PR? Does it work for you?

**Comment by splatteredbits** [comment]
I’m on vacation for a week so won’t be able to do any manual testing until then. If you could publish a prerelease version to the gallery, that would help us test easier.

**Comment by gabriel-samfira** [comment]
> I’m on vacation for a week so won’t be able to do any manual testing until then. If you could publish a prerelease version to the gallery, that would help us test easier.

ohh! Enjoy your vacation!

**Comment by gabriel-samfira** [comment]
I will go ahead and merge this as it is. I will then publish a pre-release on the powershell gallery. If anything breaks, we can revert this PR or fix whatever breaks.

**Comment by gabriel-samfira** [comment]
A pre-release version has been published. You can install it with:

```powershell
Install-Module -Name powershell-yaml -AllowPrerelease -Version 0.4.8-rc1 -Force
```

**Comment by gabriel-samfira** [comment]
FYI, I released an rc2 which handles really large integers  and properly serializes PSCustomObjects. It also builds the custom assembly we use via the dotnet SDK, properly targeting netstandard2.1 and net47.

**Pull request merged**
