### PR TITLE
Fixed: importing powershell-yaml fails if another version of YamlDotNet.dll is loaded

### PR DESCRIPTION
**Pull request by splatteredbits**

### CODE REVIEW

**Comment by splatteredbits** [comment]
Looks like the build is breaking for reasons not related to my change.

**Comment by gabriel-samfira** [comment]
Hi @splatteredbits 

Would you mind rebasing and pushing again?

**Comment by gabriel-samfira** [comment]
The issue you linked to describes a different kind of problem. In cases where multiple powershell modules ship with a certain assembly (YamlDotNet in this case), powershell will load the assemblies in the current context, once. If you try to load a different version of the same assembly later, it will err out.

Load contests allows powershell modules to have the assemblies it needs, loaded into a separate context from which it can pull those dependencies. But it's not trivial to do in powershell alone and I have had very little time to dedicate to that effort.

**Comment by gabriel-samfira** [comment]
I ended up adding load contexts here: https://github.com/cloudbase/powershell-yaml/pull/132

**Comment by splatteredbits** [comment]
Rebased and pushed.

**Comment by splatteredbits** [comment]
I'm adding a test.

**Comment by gabriel-samfira** [comment]
I am curious if this is still needed given #134. Could you check that PR and see if you still encounter the issue?

**Comment by splatteredbits** [comment]
> I am curious if this is still needed given #132 . Could you check that PR and see if you still encounter the issue?

Definitely still needs this despite #132. PR #132 removes Windows PowerShell 5.1 support, which we need.

**Comment by splatteredbits** [comment]
Test added.

**Comment by gabriel-samfira** [comment]
> > I am curious if this is still needed given #132 . Could you check that PR and see if you still encounter the issue?
> 
> Definitely still need this despite #132. PR #132 removes Windows PowerShell 5.1 support, which we need.

Understood. Let me see if there is a GitHub runner for windows server 2016. That one has PowerShell 5.1.

**Comment by KhoiKy** [comment]
Hello @gabriel-samfira, do you know when these changes will get published?

**Comment by gabriel-samfira** [comment]
Hi @KhoiKy,

There is another PR I would like to merge before we publish. This is the PR:

https://github.com/cloudbase/powershell-yaml/pull/132

Would you mind testing that PR out and let me know if it works as expected on your system?

**Pull request merged**
