### PR TITLE
Update YamlDotNet assemblies to 13.0, add support for pwsh 7.x

### LINKED ISSUE #84: Update YamlDotNet?
I found that this issue - https://github.com/cloudbase/powershell-yaml/issues/32 - can be now fixed, see https://github.com/aaubry/YamlDotNet/pull/592.

Could it be done? Is this module still maintained? Thanks.

### PR DESCRIPTION
**Pull request by Eggdale**
Howdy,

I've updated the internal YamlDotNet assemblies to 13.0 to fix #84, which allows for fixing #32 by adding the `WithIndentedSequences` option to `ConvertTo-Yaml.` The `YamlDotNet.Serialization.SerializationOptions` enum was removed in [this YamlDotNet issue](https://github.com/aaubry/YamlDotNet/issues/438), so I added it back locally.
 
Additionally, I've added a fix for pwsh 7.x which would prevent the tests from running due to pwsh not automatically loading standard references when those are loaded manually. [see here](https://github.com/PowerShell/PowerShell/issues/9599) for details.

Thanks!

### CODE REVIEW

**Comment by gabriel-samfira** [comment]
Hi @Eggdale !

This is awesome! Thank you!

I have a couple of questions. Where did you download the DLLs from? Which build?

The current release (https://github.com/aaubry/YamlDotNet/releases/tag/v13.0.0), lists https://github.com/aaubry/YamlDotNet/pull/771 as the PR which merged last into this release.  This corresponds to this build: https://ci.appveyor.com/project/aaubry/yamldotnet/builds/46071641/artifacts. 

The sha256sum from the above build with the ones in your branch and they seem to differ.

Thanks again for taking the time to make these changes!

**Comment by Eggdale** [comment]
Interesting, I pulled them out of the nuget package from [nuget package repository](https://www.nuget.org/packages/YamlDotNet/). I assumed those would be the same as the release package but they're not. Even the nuget package on the appveyor site has different binaries.

I've added a commit to use the release versions instead of those nuget versions.

Thanks!

**Comment by Eggdale** [comment]
No worries, thanks for keeping me honest!
Two things happened here: I used a more recent build for this update than the one that you list in your comment, [https://ci.appveyor.com/project/aaubry/yamldotnet/builds/46172294/artifacts](https://ci.appveyor.com/project/aaubry/yamldotnet/builds/46172294/artifacts), as well as pulling from the `bin\Release` folder instead of extracting the NuGet package. I originally submitted with the extracted NuGet package as it's what I already had on my machine, but the newest commit is using the Release binaries. I see those sums matching the ones in my commit:

```
eggdale@DESKTOP-UPL75UE:~$ wget -q -O Release-Net35.zip https://ci.appveyor.com/api/buildjobs/2adpm5ej1g96e1ss/artifacts/YamlDotNet%2Fbin%2FRelease%2FRelease-Net35.zip
eggdale@DESKTOP-UPL75UE:~$ unzip -q Release-Net35.zip
eggdale@DESKTOP-UPL75UE:~$ sha256sum YamlDotNet.dll
94f4ccbb6ea28cfb10fcfa3aa13109e4c7b3efd6aa42f55dae6e0f8fb55914b7  YamlDotNet.dll

eggdale@DESKTOP-UPL75UE:~$ wget -q -O Release-Net45.zip https://ci.appveyor.com/api/buildjobs/2adpm5ej1g96e1ss/artifacts
/YamlDotNet%2Fbin%2FRelease%2FRelease-Net45.zip
eggdale@DESKTOP-UPL75UE:~$ unzip -q Release-Net45.zip
eggdale@DESKTOP-UPL75UE:~$ sha256sum YamlDotNet.dll
9af8026704a0f7f15491fccea4e1e3aee84ec7d22cdf361ba3395b1109968960  YamlDotNet.dll

eggdale@DESKTOP-UPL75UE:~$ wget -q -O Release-NetStandard-2.1.zip https://ci.appveyor.com/api/buildjobs/2adpm5ej1g96e1ss/artifacts/YamlDotNet%2Fbin%2FRelease%2FRelease-NetStandard-2.1.zip
eggdale@DESKTOP-UPL75UE:~$ unzip -q Release-NetStandard-2.1.zip
eggdale@DESKTOP-UPL75UE:~$ sha256sum YamlDotNet.dll
9623827afa09c0f504282088bccf929ec92b5ff425515e2e5740599829493850  YamlDotNet.dll
```
Should I use a different build, or is this one sufficient?

Sorry for the confusion, still very green when it comes to open source contributions.

**Comment by Eggdale** [comment]
Thanks for the guidance, I've updated the modules accordingly.

Thanks!

**Comment by gabriel-samfira** [comment]
One last thing, which I should have noticed earlier. While the dlls are built from an open source and free project, we are still obliged to acknowledge where we got them from and distribute them with their license included in each folder (```lib/netstandard2.1```, ```lib/net35``` and ```lib/net45```) . You can copy the license from:

https://github.com/aaubry/YamlDotNet/blob/master/LICENSE.txt
https://github.com/aaubry/YamlDotNet/blob/master/LICENSE-libyaml

Sorry I didn't catch it earlier, and thanks for your patience :smile:.

**Comment by Eggdale** [comment]
Gotcha, makes sense. I didn't see them with the releases in the new version so I wasn't sure whether or not to include them manually. 

Thanks!

**Comment by gabriel-samfira** [comment]
> Gotcha, makes sense. I didn't see them with the releases in the new version so I wasn't sure whether or not to include them manually.
> 
> Thanks!

They are not usually included in the binary builds. If we're simply consuming them for our needs, we don't really need to keep the license text with the binaries, but we're redistributing them in our own project, so we have to do that.

Thanks for taking the time to contribute these changes!

**Pull request merged**
